### ISSUE TITLE
Sweet Alert Deprecated Methods

### ISSUE THREAD

**Issue by michaelmagero** [uxweb/sweet-alert#104] opened 2019-10-26 03:55 UTC
Am getting this error in google chrome how can i remove it

> SweetAlert2: "setDefaults" & "resetDefaults" methods are deprecated in favor of "mixin" method and will be removed in the next major release. For new projects, use "mixin". For past projects already using "setDefaults", support will be provided through an additional package.

**Comment by AmjadIqbal** [comment] 2019-11-05 17:29
Hey , Have you try my laravel sweetalert package , it's very simple to use . i have also provided live chat https://amjadiqbal.github.io/sweetalert/

**Comment by thewebartisan7** [comment] 2019-11-22 10:09
Same as here https://github.com/uxweb/sweet-alert/issues/106

**Comment by thewebartisan7** [comment] 2019-11-22 11:03
How you get this? I can't reproduce.

**Comment by AmjadIqbal** [comment] 2019-11-22 14:13
hey @thewebartisan7  have you try this package , which support almost every function , and also you can make your own model boxes with sweetalert , https://amjadiqbal.github.io/sweetalert/

**Comment by thewebartisan7** [comment] 2019-11-23 12:23
Thanks for sharing. I started yesterday refactor this to support sweetalert2, and since I do already many progress, I will keep mine upgraded. However, I would check into your to see what I can implement in mine. The link https://github.com/amjadIqbal/sweetalert seem broken. Did you delete it or what?

**Comment by AmjadIqbal** [comment] 2019-11-23 14:03
@thewebartisan7  yes i delete the respository because my friend told me that you have created a copy of my laravel sweetalert package ,  what you think about it , ? 
If you want to talk with me then come to my documentation page https://amjadiqbal.github.io/sweetalert/ and start chatting with me i will talk you there

**Comment by uxweb** [comment] 2019-12-23 18:18
@mowimisha 

I'm doing a review of the new api for the sweet alert js library. This seems as a breaking change and maybe a new major version will be released.

**Comment by uxweb** [comment] 2019-12-24 01:13
@mowimisha I think that you are using another sweet alert js library. I didn't know two of them exists. This PHP package is designed to work with https://github.com/t4t5/sweetalert and not https://github.com/sweetalert2/sweetalert2.

**Closed as completed by uxweb** 2019-12-24 01:13 UTC
